spring:
  shardingsphere:

    datasource:

      master:

        type: com.zaxxer.hikari.HikariDataSource

        driverClassName: com.mysql.cj.jdbc.Driver

        jdbcUrl: jdbc:mysql://localhost:13306/datech_zjfh?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT

        username: root

        password: 123456

      slave0:

        type: com.zaxxer.hikari.HikariDataSource

        driverClassName: com.mysql.cj.jdbc.Driver

        jdbcUrl: jdbc:mysql://127.0.0.1:13307/datech_zjfh?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT

        username: root

        password: 123456

      names: master,slave0

    props:

      sql.show: true

    masterslave:

      load-balance-algorithm-type: round_robin

    sharding:

      master-slave-rules:

        master:

          master-data-source-name: master

          slave-data-source-names: slave0
  redis:
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 10000
      database: 0
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379, 127.0.0.1:26380, 127.0.0.1:26381
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB  # 默认单个文件的上传大小时1MB
      max-request-size: 1024MB # 默认一次上传的总文件大小为10MB


server:
  port: 9006
  ssl:
    key-alias: datech
    key-store-password: datech123
    key-store-type: PKCS12
    key-store: classpath:datech.p12

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #扫描mapper下的所有xml文件
  type-aliases-package: com.datech.zjfh.api.entity   #扫描实体类包/配置别名
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.datech.zjfh.api.mapper: debug

ftp:
  hostname: 192.168.2.113
  port: 21
  username: admin
  password: 123456
#  basePath: /home/vsftpd/admin/upgrade/Datarnd.msi
  remotePath: upgrade
  fileName: Datarnd.msi
  version: 2.0

client:
  version: 2.0
  #nginx地址
  url: http://192.168.2.113/upgrade/v2.0/Datarnd.msi
  isForce: 0

#ivs1800:
#  url: https://192.168.2.111:18531
#  username: datarnd
#  password: Datarnd@234


alarmServer:
  receiveAddr: https://192.168.2.103:9026/ivs/callback



