version: '3'
services:
#  mysql:
#    image: mysql:8.0
#    container_name: datarnd-mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql123qwe
#      TZ: Asia/Shanghai
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql/data:/var/lib/mysql
#      - ./mysql/config:/etc/mysql/conf.d
#    command:
#      mysqld
#      --innodb-buffer-pool-size=512M
#      --default-time-zone=+8:00
#      --max_connections=1000
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --default-authentication-plugin=mysql_native_password
#    networks:
#      - datarndNet
#
#  redis:
#    image: redis:6.2.7
#    container_name: datarnd-redis
#    restart: always
#    ports:
#      - 6379:6379
#    privileged: true
#    command: redis-server /etc/redis/redis.conf --appendonly yes
#    volumes:
#      - ./redis/data:/data
#      - ./redis/conf/redis.conf:/etc/redis/redis.conf
#    networks:
#      - datarndNet
#
#  ngnix:                                          #服务名称，名称可自定义
#    container_name: datarnd-nginx              #容器名称，可自定义
#    image: nginx                                   # 镜像名称
#    restart: always
#    ports:                                     # 容器和服务器对应的端口映射，每次新增一个站点之后一定要在这里把对应的端口映射加上，不然肯定会404
#      - 80:80
#      - 8080:8080
#      - 8081:8081
#      - 8082:8082
#    privileged: true
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/logs:/var/log/nginx
#      - ./nginx/html:/usr/share/nginx/html
#      - /etc/letsencrypt:/etc/letsencrypt
#      - /etc/localtime:/etc/localtime
#    networks:
#      - datarndNet


  zjfh-api:
    image: datech/zjfh-api
    restart: always
    volumes:
      - ./api/logs:/u01/application-logs/api
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    ports:
      - "9006:9006"
    depends_on:
      - mysql
      - redis
    networks:
      - datarndNet

#  zjfh-alarm:
#    image: datech/zjfh-alarm
#    restart: always
#    volumes:
#      - ./alarm/logs:/u01/application-logs/alarm
#      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
#    ports:
#      - "9016:9016"
#      - "9026:9026"
#    depends_on:
#      - mysql
#      - redis
#      - zjfh-api
#    networks:
#      - datarndNet



networks:
  datarndNet:
    driver: bridge








