spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://datarnd-mysql:3306/datech_zjfh?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql123qwe
  redis:
    database: 0
    host: datarnd-redis
    port: 6379
    password: redis123qwe
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 9006
  ssl:
    key-alias: datech
    key-store-password: datech123
    key-store-type: PKCS12
    key-store: classpath:datech.p12

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #扫描mapper下的所有xml文件
  type-aliases-package: com.datech.zjfh.api.entity   #扫描实体类包/配置别名
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.datech.zjfh.api.mapper: debug

#ftp:
#  hostname: 192.168.2.113
#  port: 21
#  username: admin
#  password: 123456
#  save-path: /home/vsftpd/admin

client:
  version: 0
  #nginx地址
  url:  # http://172.10.60.31/upgrade/v2.0/Datarnd.msi
  isForce: 0

ivs1800:
  url: https://172.10.60.6:18531
  username: datarnd
  password: Datarnd@234


alarmServer:
  receiveAddr: https://172.10.60.31:9026/ivs/callback

projectName: 南宁市铁路局
tokenExpireTime: 1200


